sudo: required
services:
  - docker

before_install:
  - docker image build -t react-client-test -f ./client/dev.Dockerfile ./client

script:
  - docker container run react-client-test npm run test -- --coverage

after_success:
  - docker image build -t imranaskem/complex-react-client ./client
  - docker image build -t imranaskem/complex-node-server ./server
  - docker image build -t imranaskem/complex-nginx ./nginx
  - docker image build -t imranaskem/complex-node-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push imranaskem/complex-react-client
  - docker push imranaskem/complex-node-server
  - docker push imranaskem/complex-nginx
  - docker push imranaskem/complex-node-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-eu-west-2-108379538206"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY